title: Ressources pour les étudiants de l'UFR AES-EG
description: Ce site rassemble des ressources mises à disposition des étudiants de l’UFR AES-Économie-Gestion de l’Université Paris 8
theme: jekyll-theme-cayman
