theme: jekyll-theme-slate
title: [Ressources pour les étudiants de l'UFR AES-EG]
description: [Ce site rassemble les ressources mises à disposition des enseignants de l’UFR AES-Économie-Gestion de l’Université Paris 8]
